CREATE TABLE USER(USERID VARCHAR(20) PRIMARY KEY, USERNAME VARCHAR(255), PASSWORD VARCHAR(10) NOT NULL);
CREATE TABLE ADDRESS(USERID VARCHAR(20) PRIMARY KEY, ADDRESS VARCHAR(255), CITY VARCHAR(255),EMAILID VARCHAR(255),  FOREIGN KEY(USERID) REFERENCES USER(USERID));
CREATE TABLE CATEGORY(CATEGORYCODE VARCHAR(20) PRIMARY KEY NOT NULL, CATEGORYNAME VARCHAR(255));
CREATE TABLE PRODUCTORDER(ORDERID VARCHAR(20) PRIMARY KEY NOT NULL, USERID VARCHAR(255), TOTALPRICE  DECIMAL(18,2), QUANTITY INT,PRODUCTCODE VARCHAR(255), STATUS  VARCHAR(255),
FOREIGN KEY(USERID) REFERENCES USER(USERID));
CREATE TABLE PRODUCT(PRODUCTCODE VARCHAR(20) PRIMARY KEY NOT NULL, PRODUCTNAME VARCHAR(255), PRODUCTDESC VARCHAR(255),  PRODUCTPRICE FLOAT);
CREATE TABLE PRODUCTIMAGE(PRODUCTCODE VARCHAR(20) PRIMARY KEY NOT NULL, IMAGE BLOB, 
FOREIGN KEY(PRODUCTCODE) REFERENCES PRODUCT(PRODUCTCODE));